// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int number = Integer.parseInt(args[0]); // parse the value of number from the coomand value

		int greaterThanHalf = 0;
		int lessThanOrEqualToHalf = 0;



		//generate random numbers N times

		for (int i = 0; i < number; i++){
			double randomValue = Math.random();
			if (randomValue > 0.5){
				greaterThanHalf ++;
				} else {
					lessThanOrEqualToHalf++;
				}
			}

			System.out.println(">0.5: " + greaterThanHalf + " times");
			System.out.println("<=0.5: " + lessThanOrEqualToHalf + " times");

			if (lessThanOrEqualToHalf != 0) {
				double ratio = (double) greaterThanHalf / lessThanOrEqualToHalf;
				System.out.println("Ratio: " + ratio);
			} else {
				System.out.println("ratio: undefined (division by zero)");
			}
			

		}








	}

